import { Providers } from "../lib/providers";
import ScreenGuard from "../lib/ScreenGuard";
import "./globals.css"; 

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#1B1740]">
        <Providers>
          <ScreenGuard>
            {children}
          </ScreenGuard>
        </Providers>
      </body>
    </html>
  )
}
